language: julia

julia:
  - 1.0
  - nightly

notifications:
  email: false

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
    - os: windows
  allow_failures:
    - julia: nightly
    - os: windows

script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("SatelliteDynamics"; coverage=true)'
  
after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'  
  - julia --project -e 'import Pkg; Pkg.add("Documenter"); Pkg.add("PlotlyJS");'
  - julia --project ./docs/make.jl
    