language: julia

os:

julia:
  - 1.0
  - nightly

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
  allow_failures:
    - julia: nightly

script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("SatelliteDynamics"; coverage=true)'
  
after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'  
  - julia --project -e 'import Pkg; Pkg.add("Documenter");'
  - julia --project ./docs/make.jl
    