language: julia

julia:
  - 1.0
  - nightly

notifications:
  email: false

matrix:
  include:
    - os: linux
    - os: osx
  allow_failures:
    - julia: nightly

  before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cask install basictex; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq x11-apps libxt6 libxrender1 libxext6 libgl1-mesa-glx qtbase5-dev qtdeclarative5-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export GKSwstype=svg; fi

script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("SatelliteDynamics"; coverage=true)'

# After successfuly build submit coverage report and deploy updated documentation
# But limit deployment to the linux worker so this is done only once.
after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then julia --project -e 'import Pkg; Pkg.add("Documenter");'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then julia --project -e 'import Pkg; Pkg.add("Plots"); Pkg.add("LaTeXStrings")'; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then julia --project ./docs/make.jl; fi
    